apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: bookinfo-peer-auth
  namespace: bookinfo      
spec:
  # selector:
  #   matchLabels:
  #     app: reviews
  mtls:
    mode: STRICT
