meshConfig:
  enableTracing: true
  defaultConfig:
    tracing: {} # Disable legacy MeshConfig tracing options
  extensionProviders:
    - name: jaeger
      opentelemetry:
        service: jaeger-collector.istio-system.svc.cluster.local
        port: 4317
telemetry:
  enabled: true